In [61]:
import pandas as pd 
import numpy as np
from sklearn import linear_model

ModuleNotFoundError: No module named 'word2number'

In [10]:
df=pd.read_csv("homeprices.csv")


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
import math 
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [19]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)

In [21]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [23]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [25]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [27]:
reg.intercept_

221323.00186540402

In [29]:
reg.predict([[3000,3,40]])

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [31]:
((112.06244194*3000)+(23388.88007794*3)+(-3231.71790863*40))+221323.00186540402

498408.25157402403

In [33]:
reg.predict([[2500,4,5]])

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [35]:
ex=pd.read_csv("hiring.csv")
ex

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [41]:
ex.experience=ex.experience.fillna("zero")
ex

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [49]:
med_score=math.floor(ex['test_score(out of 10)'].mean())

In [51]:
med_score

7

In [53]:
ex['test_score(out of 10)']=ex['test_score(out of 10)'].fillna(med_score)

In [55]:
ex

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [65]:
pip install word2number

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=bf0211412a8c2c56fd42b6cc1cb11ab1b79a5a742915074fbcf5e18f387987d8
  Stored in directory: /Users/nishanishmitha/Library/Caches/pip/wheels/5b/79/fb/d25928e599c7e11fe4e00d32048cd74933f34a74c633d2aea6
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [67]:
from word2number import w2n

In [69]:
ex.experience = ex.experience.apply(w2n.word_to_num)
ex

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [57]:
reg_ex=linear_model.LinearRegression()
reg_ex.fit(ex[['experience','test_score(out of 10)','interview_score(out of 10)']],ex['salary($)'])

ValueError: could not convert string to float: 'zero'

In [ ]:
ex.predict([[two,9,6]]